### ISSUE TITLE
Certain NPCs have their dialouge censored

### ISSUE THREAD

**Issue by Sirachacha** [taj-ny/skyblockchatfilter#1]
Video Evidence: https://youtu.be/uHByk4ViDU0

No additional mods were present, and this was a clean installation of Minecraft. Attempts to look in the logged files of SBC did not include the NPCs' dialogue in "spam.txt". Their dialogue is likely completely erased from the chat bar. However, actual player spam was included in the "spam.txt" file.

I have attached the "spam.txt" file for further evidence and a snippet of the "latest.log.txt" file. Hope it helps.

Snippet:
[12:39:02] [Client thread/ERROR]: Index: 1 Listeners:
[12:39:02] [Client thread/ERROR]: 0: NORMAL
[12:39:02] [Client thread/ERROR]: 1: ASM: io.github.taj_ny.skyblockchatfilter.listener.ChatListener@4b954cbb onChat(Lnet/minecraftforge/client/event/ClientChatReceivedEvent;)V
[12:39:02] [Client thread/FATAL]: Error executing task

[spam.txt](https://github.com/taj-ny/skyblockchatfilter/files/8000175/spam.txt)

**Comment by taj-ny** [comment]
Looks like I didn't do enough testing. There's a NullPointerException being thrown. I'll fix that soon.

**Comment by taj-ny** [comment]
The filter now properly handles messages sent by players who are somehow not in the current server. The issue has been fixed in v1.1.4, which will be released soon. Thank you for your bug report.
